export const OBTER_PROJETOS = 'OBTER_PROJETOS';
export const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO';
export const ALTERAR_PROJETO = 'ALTERAR_PROJETO';
export const EXCLUI_PROJETO = 'EXCLUI_PROJETO';

export const OBTER_TAREFAS = 'OBTER_TAREFAS';
